Collections:
  - Name: STARK
    Metadata:
      Training Data: GOT10k, LaSOT, TrackingNet, MSCOCO
      Training Techniques:
        - AdamW
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/2103.17154
        Title: Learning Spatio-Temporal Transformer for Visual Tracking
    README: configs/sot/stark/README.md

Models:
  - Name: stark_st1_r50_500e_got10k
    In Collection: STARK
    Config: configs/sot/stark/stark_st1_r50_500e_got10k.py
    Metadata:
      Training Data: GOT10k
      Training Memory (GB): 8.45
      Epochs: 500
    Results:
      - Task: Single Object Tracking
        Dataset: GOT10k
        Metrics:
          AO: 68.1
          SR0.5: 77.4
          SR0.75: 62.4
    Weights: https://download.openmmlab.com/mmtracking/sot/stark/stark_st1_r50_500e_got10k/stark_st1_r50_500e_got10k_20220223_125400-40ead158.pth

  - Name: stark_st2_r50_50e_got10k
    In Collection: STARK
    Config: configs/sot/stark/stark_st2_r50_50e_got10k.py
    Metadata:
      Training Data: GOT10k
      Training Memory (GB): 2.31
      Epochs: 50
    Results:
      - Task: Single Object Tracking
        Dataset: GOT10k
        Metrics:
          AO: 68.3
          SR0.5: 77.6
          SR0.75: 62.7
    Weights: https://download.openmmlab.com/mmtracking/sot/stark/stark_st2_r50_50e_got10k/stark_st2_r50_50e_got10k_20220226_124213-ee39bbff.pth

  - Name: stark_st1_r50_500e_lasot
    In Collection: STARK
    Config: configs/sot/stark/stark_st1_r50_500e_lasot.py
    Metadata:
      Training Data: GOT10k, LaSOT, TrackingNet, MSCOCO
      Training Memory (GB): 8.45
      Epochs: 500
    Results:
      - Task: Single Object Tracking
        Dataset: LaSOT
        Metrics:
          Success: 67.0
          Norm Precision: 77.3
          Precision: 71.7
    Weights: https://download.openmmlab.com/mmtracking/sot/stark/stark_st1_r50_500e_lasot/stark_st1_r50_500e_lasot_20220414_185654-9c19e39e.pth

  - Name: stark_st2_r50_50e_lasot
    In Collection: STARK
    Config: configs/sot/stark/stark_st2_r50_50e_lasot.py
    Metadata:
      Training Data: GOT10k, LaSOT, TrackingNet, MSCOCO
      Training Memory (GB): 2.31
      Epochs: 50
    Results:
      - Task: Single Object Tracking
        Dataset: LaSOT
        Metrics:
          Success: 67.8
          Norm Precision: 78.5
          Precision: 73.0
    Weights: https://download.openmmlab.com/mmtracking/sot/stark/stark_st2_r50_50e_lasot/stark_st2_r50_50e_lasot_20220416_170201-b1484149.pth

  - Name: stark_st1_r50_500e_trackingnet
    In Collection: STARK
    Config: configs/sot/stark/stark_st1_r50_500e_trackingnet.py
    Metadata:
      Training Data: GOT10k, LaSOT, TrackingNet, MSCOCO
      Training Memory (GB): 8.45
      Epochs: 500
    Results:
      - Task: Single Object Tracking
        Dataset: TrackingNet
        Metrics:
          Success: 80.5
          Norm Precision: 85.0
          Precision: 77.7
    Weights: https://download.openmmlab.com/mmtracking/sot/stark/stark_st1_r50_500e_trackingnet/stark_st1_r50_500e_lasot_20220414_185654-9c19e39e.pth

  - Name: stark_st2_r50_50e_trackingnet
    In Collection: STARK
    Config: configs/sot/stark/stark_st2_r50_50e_trackingnet.py
    Metadata:
      Training Data: GOT10k, LaSOT, TrackingNet, MSCOCO
      Training Memory (GB): 2.31
      Epochs: 50
    Results:
      - Task: Single Object Tracking
        Dataset: TrackingNet
        Metrics:
          Success: 81.4
          Norm Precision: 86.2
          Precision: 79.0
    Weights: https://download.openmmlab.com/mmtracking/sot/stark/stark_st2_r50_50e_trackingnet/stark_st2_r50_50e_lasot_20220416_170201-b1484149.pth
